Repository mdl29/donkeycarLPH, pull requests merged in 2022-06, with the labels that each got.

#108 :sparkles: [Backend] Fixes #107, add cars events and laptimers events.
  backend/donkeycarmanager/crud/cars.py
  backend/donkeycarmanager/crud/driving_waiting_queue.py
  backend/donkeycarmanager/crud/laptimers.py
  backend/donkeycarmanager/emitters/__init__.py
  backend/donkeycarmanager/emitters/cars.py
  backend/donkeycarmanager/emitters/laptimers.py
  backend/donkeycarmanager/routers/cars.py
  backend/donkeycarmanager/routers/laptimers.py
  backend/donkeycarmanager/schemas.py
  backend/socketioTestPage.html
  doc/donkeycarManager/event-spec-asyncio.yaml
Labels: enhancement

#114 [3dParts] :sparkles: Adding support for circuit border
  3dDesigns/circuit-border/SupportBarriereDonkeyCar.scad
  3dDesigns/circuit-border/SupportBarriereDonkeyCar.stl
Labels: 3D print ready

#120 :wrench: [CI] Fixes #119 add ritorizo to tursted forks
  .github/workflows/raspberrypi-image-build-needed.yml
Labels: enhancement

#115 [3dParts] Update ps4 anti-theft
  3dDesigns/anti-theft-ps4/lowPart.stl
  3dDesigns/anti-theft-ps4/ps4AntiTheft.stl
  3dDesigns/anti-theft-ps4/upPart.stl
Labels: enhancement, Software, 3D print ready

#124 Resolves #121 : Add IR-lap-timer to ansible recipe
  ansible/donkeycar.yml
  ansible/roles/IR-lap-timer/tasks/main.yml
Labels: enhancement, Software

#128 Resolves #125 : Raise chassis
  3dDesigns/car-chassis/chassis.stl
  3dDesigns/car-chassis/front-chassis.stl
  3dDesigns/car-chassis/preview.png
  3dDesigns/car-chassis/rear-chassis.stl
Labels: enhancement, 3D print ready

#136 :bug: [Car + Backend] Fixing websocket issue and other bugs
  ansible/roles/mycar/files/requirements.txt
  backend/donkeycarmanager/app.py
  backend/donkeycarmanager/dependencies.py
  backend/donkeycarmanager/routers/workers.py
Labels: bug

#134 add IR module activation in rc.local
  ansible/roles/IR-lap-timer/tasks/main.yml
Labels: enhancement, Software

#139 :sparkles: Race and Laptimers implemented
  ansible/roles/mycar/files/custom/irlaptimer.py
  ansible/roles/mycar/files/custom/manager/car_manager.py
  ansible/roles/mycar/files/custom/manager/car_manager_api_service.py
  ansible/roles/mycar/files/custom/manager/job_manager.py
  ansible/roles/mycar/files/custom/manager/jobs/job.py
  ansible/roles/mycar/files/custom/manager/jobs/job_drive.py
  ansible/roles/mycar/files/custom/manager/race_service.py
  ansible/roles/mycar/files/custom/manager/schemas.py
  ansible/roles/mycar/files/manage.py
  backend/donkeycarmanager/app.py
  backend/donkeycarmanager/models.py
  backend/donkeycarmanager/schemas.py
Labels: enhancement

#152 :bug: [Backend] Fixes #148 Job without workers can be cancelled
  backend/donkeycarmanager/crud/jobs.py
  backend/donkeycarmanager/crud/jobs_read.py
  backend/donkeycarmanager/emitters/jobs.py
  backend/donkeycarmanager/emitters/jobs_without_job_sched.py
  backend/donkeycarmanager/routers/jobs.py
  backend/donkeycarmanager/services/async_job_scheduler.py
Labels: bug

#163 :bug: [Backend] Fixes #162 Heartbeat manager wrong dependency injection
  backend/donkeycarmanager/app.py
  backend/donkeycarmanager/dependencies.py
  backend/donkeycarmanager/worker_heartbeat_manager.py
Labels: bug
