Repository mdl29/donkeycarLPH, pull requests merged in 2022-07, with the labels that each got.

#171 :sparkless: [Car + backend] remove zeroconf
  ansible/roles/car-config/files/config-ntp.sh
  ansible/roles/car-config/files/ntp.service
  ansible/roles/mycar/files/custom/helpers/zeroconf.py
  ansible/roles/mycar/files/custom/manager/car_manager.py
  ansible/roles/mycar/files/custom/manager/job_manager.py
  ansible/roles/mycar/files/custom/manager/jobs/job.py
  ansible/roles/mycar/files/donkeycar.service
  ansible/roles/mycar/files/manage.py
  backend/.idea/runConfigurations/Start_donkeycarmanager__uvicorn_.xml
  backend/donkeycarmanager/app.py
Labels: enhancement

#109 ✨ Add donkeycar manager front
  .gitignore
  donkeycarManagerFront/.editorconfig
  donkeycarManagerFront/.eslintignore
  donkeycarManagerFront/.eslintrc.js
  donkeycarManagerFront/.gitignore
  donkeycarManagerFront/README.md
  donkeycarManagerFront/build/build.js
  donkeycarManagerFront/build/check-versions.js
  donkeycarManagerFront/build/logo.png
  donkeycarManagerFront/build/utils.js
  donkeycarManagerFront/build/vue-loader.conf.js
  donkeycarManagerFront/build/webpack.base.conf.js
  donkeycarManagerFront/build/webpack.dev.conf.js
  donkeycarManagerFront/build/webpack.prod.conf.js
  donkeycarManagerFront/config/dev.env.js
  donkeycarManagerFront/config/index.js
  donkeycarManagerFront/config/prod.env.js
  donkeycarManagerFront/index.html
  donkeycarManagerFront/package-lock.json
  donkeycarManagerFront/package.json
  donkeycarManagerFront/src/App.vue
  donkeycarManagerFront/src/assets/controller/PS4_Circle.png
  donkeycarManagerFront/src/assets/controller/PS4_Cross.png
  donkeycarManagerFront/src/assets/controller/PS4_Diagram.png
  donkeycarManagerFront/src/assets/controller/PS4_Diagram_Simple.png
  donkeycarManagerFront/src/assets/controller/PS4_Dpad.png
  donkeycarManagerFront/src/assets/controller/PS4_Dpad_Down.png
  donkeycarManagerFront/src/assets/controller/PS4_Dpad_Left.png
  donkeycarManagerFront/src/assets/controller/PS4_Dpad_Right.png
  donkeycarManagerFront/src/assets/controller/PS4_Dpad_Up.png
  donkeycarManagerFront/src/assets/controller/PS4_L1.png
  donkeycarManagerFront/src/assets/controller/PS4_L2.png
  donkeycarManagerFront/src/assets/controller/PS4_Left_Stick.png
  donkeycarManagerFront/src/assets/controller/PS4_Left_Stick_Click.png
  donkeycarManagerFront/src/assets/controller/PS4_Options.png
  donkeycarManagerFront/src/assets/controller/PS4_R1.png
  donkeycarManagerFront/src/assets/controller/PS4_R2.png
  donkeycarManagerFront/src/assets/controller/PS4_Right_Stick.png
  donkeycarManagerFront/src/assets/controller/PS4_Right_Stick_Click.png
  donkeycarManagerFront/src/assets/controller/PS4_Share.png
  donkeycarManagerFront/src/assets/controller/PS4_Square.png
  donkeycarManagerFront/src/assets/controller/PS4_Touch_Pad.png
  donkeycarManagerFront/src/assets/controller/PS4_Triangle.png
  donkeycarManagerFront/src/assets/crown.png
  donkeycarManagerFront/src/assets/donkeycar.png
  donkeycarManagerFront/src/components/carView.vue
  donkeycarManagerFront/src/components/clientView.vue
  donkeycarManagerFront/src/components/dashboard.vue
  donkeycarManagerFront/src/components/home.vue
  donkeycarManagerFront/src/components/raceView.vue
  donkeycarManagerFront/src/components/register.vue
  donkeycarManagerFront/src/components/textIcon.vue
  donkeycarManagerFront/src/components/waitingBoard.vue
  donkeycarManagerFront/src/components/waitingText.vue
  donkeycarManagerFront/src/fonts/AzeretMono-VariableFont_wght.ttf
  donkeycarManagerFront/src/js/classement.js
  donkeycarManagerFront/src/js/service.js
  donkeycarManagerFront/src/main.js
  donkeycarManagerFront/src/router/index.js
  donkeycarManagerFront/static/.gitkeep
Labels: Software

#182 :bug: [Backend] Fixes worker filter issues
  backend/donkeycarmanager/crud/workers_read.py
Labels: bug
