Repository mdl29/donkeycarLPH, pull requests merged in 2022-05, with the labels that each got.

#66 Resolves #57 : Create camera cover holder
  3dDesigns/anti-theft-ps4/README.md
  3dDesigns/anti-theft-ps4/lowPart.stl
  3dDesigns/anti-theft-ps4/preview.png
  3dDesigns/anti-theft-ps4/ps4AntiTheft.stl
  3dDesigns/anti-theft-ps4/upPart.stl
  3dDesigns/camera-cover/README.md
  3dDesigns/camera-cover/camera-cover-holder.stl
  3dDesigns/camera-cover/camera-cover.zip
  3dDesigns/camera-cover/preview.png
  3dDesigns/car-chassis/README.md
  3dDesigns/car-chassis/chassis.stl
  3dDesigns/car-chassis/front-chassis.stl
  3dDesigns/car-chassis/preview.png
  3dDesigns/car-chassis/rear-chassis.stl
  README.md
Labels: documentation, enhancement

#65 Resolves #56 : Add a LED indicator
  ansible/roles/raspi-config/tasks/main.yml
Labels: enhancement, Software, Hardware

#68 [ Doc ] Resolves #56 update electronic doc
  doc/schema/schema-electronique.png
  doc/schema/shema-electronique.fzz
Labels: enhancement, Hardware

#64 Resolves #55 : [Ansible] Shortcut to take full resolution picture (check camera quality)
  ansible/roles/ps4-controller/tasks/main.yml
  ansible/roles/ps4-controller/templates/ds4drv.conf.j2
  ansible/roles/ps4-controller/templates/picture.sh.j2
Labels: enhancement, Software

#84 :sparkles: Fixes #83 'raspberrypi-image / build' check passed always executed
  .github/workflows/no-raspberrypi-image-build.yml
  .github/workflows/raspberrypi-image-build-needed.yml
Labels: enhancement

#87 :bug: Fixes #86, trigger post comment
  .github/workflows/raspberrypi-image-build-needed.yml
Labels: bug

#90 :bug: [CI] Fixes #89, fetch code form right repository
  .github/workflows/raspberrypi-image-build-needed.yml
Labels: bug

#93 :bug: [CI] Fixes #92, concurrency for github action
  .github/workflows/raspberrypi-image-build-needed.yml
Labels: bug

#95 :bug: [CI] fixes #94, ref and head_ref image path naming issues
  .github/workflows/raspberrypi-image-build-needed.yml
Labels: bug

#97 :bug: [CI] Fixes #96, in PR comment use pull_request sha not upstream…
  .github/workflows/raspberrypi-image-build-needed.yml
Labels: bug

#99 :bug: [CI] Fixes #96, image file path errors
  .github/workflows/raspberrypi-image-build-needed.yml
Labels: bug

#80 Architecture thinking donkeycar manager tool
  backend/.gitignore
  backend/.idea/.gitignore
  backend/.idea/backend.iml
  backend/.idea/inspectionProfiles/profiles_settings.xml
  backend/.idea/misc.xml
  backend/.idea/modules.xml
  backend/.idea/runConfigurations/Start_donkeycarmanager__uvicorn_.xml
  backend/.idea/vcs.xml
  backend/README.md
  backend/docker-compose.yml
  backend/donkeycarmanager/__init__.py
  backend/donkeycarmanager/crud/__init__.py
  backend/donkeycarmanager/crud/cars.py
  backend/donkeycarmanager/crud/driving_waiting_queue.py
  backend/donkeycarmanager/crud/laptimers.py
  backend/donkeycarmanager/crud/players.py
  backend/donkeycarmanager/crud/races.py
  backend/donkeycarmanager/database.py
  backend/donkeycarmanager/dependencies.py
  backend/donkeycarmanager/helpers/__init__.py
  backend/donkeycarmanager/helpers/socker_io_manager.py
  backend/donkeycarmanager/helpers/utils.py
  backend/donkeycarmanager/main.py
  backend/donkeycarmanager/models.py
  backend/donkeycarmanager/routers/__init__.py
  backend/donkeycarmanager/routers/cars.py
  backend/donkeycarmanager/routers/driving_waiting_queue.py
  backend/donkeycarmanager/routers/laptimers.py
  backend/donkeycarmanager/routers/players.py
  backend/donkeycarmanager/routers/races.py
  backend/donkeycarmanager/schemas.py
  backend/setup.cfg
  backend/setup.py
  backend/socketioTestPage.html
  doc/donkeycarManager/DataStructure.drawio
  doc/donkeycarManager/DataStructure.png
  doc/donkeycarManager/DonkeycarBoothManagerArchitecture.drawio
  doc/donkeycarManager/DonkeycarBoothManagerArchitecture.png
  doc/donkeycarManager/event-spec-asyncio.yaml
  doc/donkeycarManager/events.md
  doc/donkeycarManager/manager-features.md
Labels: documentation

#104 :wrench: [Ansible] Fixes #103, LED colors
  ansible/config/monkecar/ds4drv.env
  ansible/config/pimpcar/ds4drv.env
Labels: enhancement
