Repository mdl29/donkeycarLPH, pull requests merged in 2022-09, with the labels that each got.

#201 [ Doc ] Update electronic documentation
  doc/schema/schema-electronique.png
  doc/schema/shema-electronique.fzz
Labels: documentation, enhancement, Hardware

#202 [ Ansible ] Changing wpa conf to be able to capture 5G channels
  ansible/group_vars/all
Labels: enhancement, Software

#174 :sparkles: [Car + Back] End races
  ansible/roles/mycar/files/custom/manager/car_manager_api_service.py
  ansible/roles/mycar/files/custom/manager/jobs/job_drive.py
  ansible/roles/mycar/files/custom/manager/race_service.py
  ansible/roles/mycar/files/custom/manager/schemas.py
  backend/donkeycarmanager/crud/races.py
  backend/donkeycarmanager/emitters/races.py
  backend/donkeycarmanager/models.py
  backend/donkeycarmanager/routers/races.py
  backend/donkeycarmanager/schemas.py
  backend/socketioTestPage.html
  doc/donkeycarManager/event-spec-asyncio.yaml
Labels: bug

#198 [ Doc ] README and documentation improvements
  IR-tower/IR-tower-code/LED_IR_TX.ino
  IR-tower/IR-tower-code/PinDefinitionsAndMore.h
  IR-tower/IRremote.zip
  IR-tower/Pilier_infrarouge.pdf
  IR-tower/README.md
  IR-tower/elec-schematic.jpg
  README.md
  ansible/donkeycar.yml
  ansible/group_vars/all
  ansible/roles/mycar/defaults/main.yml
  ansible/roles/mycar/tasks/main.yml
  ansible/roles/mycar/templates/donkeycar.service.j2
  backend/README.md
  doc/assets/carView.jpg
  doc/button/Boutton_poussoir.md
  doc/button/shutdown-button.md
  donkeycarManagerFront/README.md
  donkeycarManagerFront/src/js/service.js
Labels: documentation

#190 [ Front ] Add reload button in dashboard
  donkeycarManagerFront/src/components/dashboard.vue
Labels: enhancement, Software
